### ISSUE TITLE
Embed field docs |html filter not working in 4.0

### ISSUE THREAD

**Issue by peterboorsma** [bolt/docs#1071]
This page: https://docs.bolt.cm/4.0/fields/embed#jumpbutton is telling me that I can use the `|html` filter:
`{{ record.embedded.responsive|html }}`
 but this doesn't work in Bolt 4

This page could use some more info about all embed options and how and when to use them btw ;)

**Comment by I-Valchev** [comment]
hi @pedronofuentes ,

Thanks for bringing this up.

It should be `|raw`.

But, better still, after this PR https://github.com/bolt/core/pull/1701 is merged in, you won't have to use that at all.

**Comment by I-Valchev** [comment]
Closing this one, as it's resolved in https://github.com/bolt/docs/pull/1072 and https://github.com/bolt/core/pull/1701
