### ISSUE TITLE
Link not working Bolt 4 Creating menus page

### ISSUE THREAD

**Issue by Sander-Hub** [bolt/docs#1075]
On the following page: https://docs.bolt.cm/4.0/menus, near the bottom of the article, the link to "menus in the Twig Components section" is resulting in a "500 Internal Server Error" message.

![Capture](https://user-images.githubusercontent.com/66225295/89991538-433bae80-dc84-11ea-8dd8-d52c13083335.PNG)

**Comment by antiftw** [comment]
Just checked the link https://docs.bolt.cm/twig-components/menu and it is working again. Issue can be closed.

**Comment by Sander-Hub** [comment]
Thanks for the reminder. Issue closed.
