### ISSUE TITLE
Link about menus returning 500 error

### ISSUE THREAD

**Issue by antiftw** [bolt/docs#1121]
When clicking the link (https://docs.bolt.cm/4.0/configuration/menus) 

visible on https://docs.bolt.cm/4.0/howto/simple-menu, as can be seen in the screenshot

![bolt_dead_link](https://user-images.githubusercontent.com/21287634/98925485-5570f700-24d6-11eb-83f1-2dd5e303feb7.png)

This results in the following error:

```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. 
We will fix it as soon as possible. Sorry for any inconvenience caused.
```

**Comment by I-Valchev** [comment]
Hi @antiftw , thanks for reporting it! There's a fix for it in the pipeline, albeit a little delayed.

**Comment by antiftw** [comment]
No problem, happy to help :)
