### ISSUE TITLE
Locale page error

### ISSUE THREAD

**Issue by Snowbaha** [bolt/docs#1142]
There is an error 500 in this page : https://docs.bolt.cm/4.0/locales (since 1 week)

![image](https://user-images.githubusercontent.com/3284722/108189639-40c58000-7111-11eb-80ac-dbb7e67f77e6.png)

**Comment by I-Valchev** [comment]
Hi @Snowbaha , thank you for reporting the issue!

A fix with the correct link is here: https://github.com/bolt/docs/pull/1145
