### ISSUE TITLE
Mixed up paragraph in Extensions documentation

### ISSUE THREAD

**Issue by ghost** [bolt/docs#1154]
In the file `https://github.com/bolt/docs/blob/4.0/docs/extensions/extension.md`

The third paragraph in the 'Submit to Packagist' section is garbled. It reads:

> If all went well, you can confirm the next step, and you'll now have published likely tell you why it didn't, enabling you to fix the error and to try again. your extension-to-be on Packagist. If it didn't go through, Packagist will most

I think it should read:

> If all went well, you can confirm the next step, and you'll now have published your extension-to-be on Packagist. If it didn't go through, Packagist will most likely tell you why it didn't, enabling you to fix the error and to try again.

**Comment by bobdenotter** [comment]
Fixed, thanks! 👍
