### ISSUE TITLE
bin/console bolt:setup throws [ERROR] Some errors occurred while setting up Bolt.

### ISSUE THREAD

**Issue by harrigo** [bolt/docs#1159]
Just trying to setup bolt via a mysql database and having difficulties. After entering username password etc for bolt user in setup database is created and can see tables. The command line shows below errors however:

```
 [ERROR] Some errors occurred while setting up Bolt.
 [WARNING] An error occurred when creating the database.
```

**PHP version:**
PHP 7.3.28 (cli) (built: Apr 30 2021 15:50:04) ( NTS )
**MariaDB:**
Server version: 10.0.38-MariaDB MariaDB Server

Strange as does look ok in brief navigation through and l can login to bolt and navigate around fine. Was wondering why this may.

**Comment by harrigo** [comment]
Bit premature maybe with the issue and have resolved, I noticed that the setup seems to also create the database where as in Plesk I had already created the database and user. Manually deleted database and let setup do the lot and seemed ok!

**Comment by bobdenotter** [comment]
Hmm.. Perhaps we should make it a bit more robust, so it doesn't break, if the database exists already. 🤔 💭

**Comment by harrigo** [comment]
Yeah, well think i'm just used to Magento where I needed it already created. Think a lot of other things need it already setup so it threw me for a min, you are possibly making it too easy!
