### ISSUE TITLE
How to use translations in twig templates?

### ISSUE THREAD

**Issue by AndreyChursin** [bolt/docs#1279]
I need to show the text in the footer of the template, but I don't understand how to do it.
May be there any function like: 
`{{ message('sometitle') }} `
witch takes the string from the "translations/messages.??.xlf" file and in current locale?

**Comment by bobdenotter** [comment]
There's `{{ l('foo') }}` and `{{ __('message') }}`

**Comment by AndreyChursin** [comment]
I found `{{ message|trans }}`, thanks!
