### ISSUE TITLE
When installing Bolt from "the developer way", recommend using a release branch

### ISSUE THREAD

**Issue by JoshTumath** [bolt/docs#145]
I installed Bolt using the git method, and didn't realise that I was therefore installing from the bleeding-edge builds, so I was having a few problems due to its instability.

Maybe the docs should recommend cloning from the latest release branch.

**Comment by GawainLynch** [comment]
Yes, good point!  

We only last weekend branched `release/2.0` and master became 2.1-alpha tracking, and like a lot of developers we forget that people not following every machination on IRC might miss points like that.

**Comment by GawainLynch** [comment]
PR submitted, should be merged soon!

**Comment by JoshTumath** [comment]
Awesome. Thanks for the quick response too! :)
