### ISSUE TITLE
Caveats of installing through Composer?

### ISSUE THREAD

**Issue by Pinpickle** [bolt/docs#154]
The docs tell you how to install through Composer, but as a lot the application lives outside of vendor (such as bolt-public), I feel like one could run into issues with updating a later release of Bolt.

Even if there isn't an issue, a mention of that will do a lot to calm down unsure minds as using Composer makes a whole lot more sense than my current workflow (updating through Git), as it allows for easy downgrading and leads to a smaller repo. If there are any caveats, this should definitely be documented.

**Comment by gerkirill** [comment]
Regarding "Installing Bolt as a composer package" documentation. There are caveats and it is not possible to install bolt just by following the documentation. E.g. composer.json should contain "minimum-stability": "dev", "prefer-stable": true. Both params are required to successfully install and run last release which is 2.2.13.

Also it is easier to create not documented "Bolt\\Composer\\ScriptHandler::bootstrap" composer command and execute it. It is much more helpful for first-time setup than documented "Bolt\\Composer\\ScriptHandler::installAssets". At least it generates index.php which calls  $app->initialize(); before $app->run(); and this is not mentioned in bolt docs at all.

"extra" section in composer.json is not documented well. It is not clear which functionality is affected by the "bolt-web-dir" and "bolt-app-dir" values. And bolt-app-dir seems not documented.

**Comment by GawainLynch** [comment]
Ass the install documentation was re-written for Bolt 3.0 last year. This should be addressed.

If not, PRs most welcome to update the information with more, um, information :smile:
