### ISSUE TITLE
More info in docs

### ISSUE THREAD

**Issue by gwbonline** [bolt/docs#167]
Maybe the documentation can be updated with some info about files that aren't updated with a new release. On Bolts website I can find updated versions of files like config.yml. I don't upload these when I install a new version of Bolt. But why are those files updated? When do I have to use them? Do I have to edit my existing files (like config.yml) manually with new additions from the updated files?

The same with composer.json.dist and composer.lock.dist. Why are these files in the Bolt folder (download). Do I have to use them?

I also like to read more about field definitions. There are several definitions (like checkbox) that have one or two lines of explanation. Is it possible to add some more extended info and or a example?

**Comment by GawainLynch** [comment]
Docs have been heavily revised over the last two years, I would suggest that these needs are covered and there is more coming as human resources become available.
