### ISSUE TITLE
Viewing website with 127.0.0.1/'project'/ instead of 127.0.0.1/'project'/index.php with Wamp

### ISSUE THREAD

**Issue by Krands** [bolt/docs#169]
When you just want to create Bolt templates on Windows without anyone else to see it, you may want to use *Wamp Server*.

Once you installed Bolt and started to see how it looks so far via the *dashboard*, you will use the *View Site* link. The problem is that the link directs to 127.0.0.1/'project'/, and it causes an error : **The debugbar cannot be found, it will ask you to open the Profiler and might return a 404 error because the Profiler cannot be found either** because your local website debugbar appears on 127.0.0.1/'project'/index.php where the *View Site* goes to 127.0.0.1/'project'/.

To make everybody okay, look at
`wamp\bin\apache\apache2.4.9\conf\httpd.conf`

Open this file with Notepad++, Sublime Text, Brackets, etc... and go to the line 154, then you will see
`#LoadModule rewrite_module modules/mod_rewrite.so` 

Apache does not read it because of the #. Erase it, save the file, and restart Wamp.

Now you can display 127.0.0.1/'project'/and the debugbar without error.
Also, you don't have to get the *index.php* in your URL anymore.

**Comment by ProfoundGames** [comment]
Did a PR on [requirements.md](https://github.com/bolt/docs/blob/master/source/requirements.md) to make it more clearer that mod_rewrite MUST be enabled.

[Pull Request #168](https://github.com/bolt/docs/pull/168 )

**Comment by bobdenotter** [comment]
Closing, because this was merged in!
