### ISSUE TITLE
dsduit / helios-html5up not working

### ISSUE THREAD

**Issue by awrog** [bolt/docs#196]
I'm using try.bolt.cm/ to get an idea of bolt cms
I chose the dsduit/helios-html5up theme,
Execpt for the frontpage (which looks great!), it does not seem to work.
Upon clicking any menu-item it it throws a Bolt fatal error.
Can this be fixed or can I fix it myself?

**Comment by xiaohutai** [comment]
It's possible that the menu links (i.e. pages) aren't working because there's nothing in the database yet.

**Comment by awrog** [comment]
xiaohutai, thanks for your reply.
No that's not it, the pages, entries and showcases are in the database.

After logging in in the backend the error becomes more clear:
Symfony \ Component \ HttpKernel \ Exception \ HttpException
Rendering Bestiarum vero nullum iudicium puto. failed: Template "record.twig" is not defined ().

Clicking on [All Pages] also gives the following error:
Rendering pages failed: Template "listing.twig" is not defined ().

Any ideas?

**Comment by rossriley** [comment]
@awrog thanks for spotting that, I think somewhere in the last few minor versions there's been something changed slightly  in Bolt that has caused a problem with the template files being found. We'll hopefully have a fix up in the next hour or so.

**Comment by awrog** [comment]
Great!

On Wed, Apr 29, 2015 at 9:54 AM, Ross Riley <notifications@github.com>
wrote:

> @awrog <https://github.com/awrog> thanks for spotting that, I think
> somewhere in the last few minor versions there's been something changed
> slightly in Bolt that has caused a problem with the template files being
> found. We'll hopefully have a fix up in the next hour or so.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bolt/docs/issues/196#issuecomment-97338361>.
>



-- 
Met vriendelijke groet,

Arno Rog

**Comment by awrog** [comment]
@rossriley Any update? I was hoping 2.1.8 had solved the errors.

**Comment by awrog** [comment]
Can someone contact Derk Duit to fix the Helios theme?

**Comment by bobdenotter** [comment]
@awrog I'll ping him! ^_^

**Comment by rossriley** [comment]
for reference there's just a missing record.twig and listing.twig template.

**Comment by awrog** [comment]
I guess it would not help if I add them from another theme?
So to be clear, this theme has never worked?

**Comment by SahAssar** [comment]
Closing this, I have started a thread in the forums to track progress on this: https://discuss.bolt.cm/d/25-theme-compatability-with-2-2-2-3-continuation-of-3731
