### ISSUE TITLE
Feature request: Give docs site favicon that is different from Bolt back-end favicon

### ISSUE THREAD

**Issue by evertalbers** [bolt/docs#245]
I often have the docs site open in one browser tab and the backend of a site that I'm building in another. Both tabs then show the same favicon. "Confusing" is too big a word, but I could dedicate 4 more braincells to the actual development if both favicons were different. 

Just a different colour would be enough for me, but maybe colourblind users would prefer a different form.

**Comment by GawainLynch** [comment]
@rossriley did make a pink one for the extensions market place during 2.0-dev :laughing:

**Comment by evertalbers** [comment]
Or use an owl for the docs ;-)
Bopp will love it.

**Comment by GawainLynch** [comment]
I, personally, have zero objections to something and PRs talk… :wink: 

Bopp has well thought out ideas on these things but he might have his mind in the great wide… um… open… right now :grin:

**Comment by bobdenotter** [comment]
Did someone mention owls? 

http://i.imgur.com/lQnV8tI.gifv

**Comment by evertalbers** [comment]
I have not figured out how to upload binary stuff to GitHub via my browser for a PR and I don't feel like forking on my HD for jut 2 wee icons, so I hope you don't mind me linking to them here:
http://streeff.nl/clients/1509_Bolt/bolt-favicon.zip

So, just for the docs site. Feel free to refuse them if you're not happy about the red, or something.

**Comment by GawainLynch** [comment]
Fixed in #826 with shiny new favions — ![](https://github.com/bolt/docs/blob/site/web/images/favicon-32x32.png?raw=true)
