### ISSUE TITLE
The "available" test seems to be missing in bolt

### ISSUE THREAD

**Issue by zomars** [bolt/docs#247]
And it still remains in the docs:

https://docs.bolt.cm/templatetags#available

When I try to use it:

```
{% if 'boltforms' is available %}
    {{ boltforms() }}
{% endif %}
```

I get this error:

![bolt-test-error](https://cloud.githubusercontent.com/assets/3504472/10006463/a651102c-607a-11e5-9cd8-e569a317d2be.png)

**Comment by jadwigo** [comment]
is 'defined' what you're looking for? http://twig.sensiolabs.org/doc/tests/defined.html

```twig
{# and attributes on variables names #}
{% if foo.bar is defined %}
    ...
{% endif %}
```

**Comment by bobdenotter** [comment]
The correct code is like this: 

```
{% if Disqus is defined %}
                {# Show the Disqus comment box, if the Disqus extension is installed .. #}
                <h4>Leave a comment</h4>
                {{ Disqus.disqus() }}
{% endif %} 
```

Note, `Disqus` in this case is the Classname of the extension. No quotes should be added. 

Thanks, @zomars! We will fix this in the docs.

**Comment by zomars** [comment]
Thanks for the reply! This is the code that ended up working for me (for bolt forms at least).
```
{% if BoltForms is defined %}
    {{ boltforms() }}
{% endif %}
```
