### ISSUE TITLE
Use of *_INSERT events

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/docs#257]
Hey,

currently you can get the information if a record was created or updates from the `isCreated()` method on the event class.

There are already this `PRE_INSERT` and `POST_INSERT` events defined but they are not triggered yet.
(https://github.com/bolt/bolt/blob/master/src/Events/StorageEvents.php#L19)

I think it does make sense to trigger either the `*_SAVE` or `*_INSERT` events in the repository. 
But that means the `isCreated()` function is a little bit useless on the event. I can create a PR tomorrow to trigger the `*_INSERT` events.

The question is, do we need the `isCreated()` function or should I delete it? Maybe we can keep it and remove it in the 2.3 release?

**Comment by GawainLynch** [comment]
This belongs on `bolt/bolt` issue tracker… jump it over there and we'll get the discussion happening.

**Comment by PhillippOhlandt** [comment]
Oh yes, sorry, saw it right now :P
