### ISSUE TITLE
Ideas for new content in the Extension Area

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/docs#258]
The current Extension Area is good to begin with an extension but still not cover everything/the most of what is possible and what user may need. 

This issue should be a collection of ideas for the Extension Area. 

I start with a few things:
- [ ] Adding new routes (with and without controller class)
- [ ] Database operations
  - [ ] adding new columns in tables
  - [ ] check if tables exist or not
  - [ ] fetch, insert, update data
- [ ] Extending the backend
  - [ ] provide new menu items (read somewhere about that)
  - [ ] adding new sites to the backend
  - [ ] extend or override existing backend sites
- [ ] Not all of [this](https://docs.bolt.cm/extensions/essentials#what-can-you-do-bolt-extensions) is covered yet
- [ ] Using third party libraries
  - [ ] No support for composer packages at the moment
  - [ ] Only PSR-4 autoloading

That is my list for now, maybe I add new things in the next time and it would be cool if other people post their ideas as answer. I'll add them to the list then.

---

Please link PRs for something in the list above here so I can mark them as done

**Comment by GawainLynch** [comment]
Awesome stuff mate, thanks for making a start!

**Comment by PhillippOhlandt** [comment]
Update, added:
- Using third party libraries
  - No support for composer packages at the moment
  - Only PSR-4 autoloading

**Comment by GawainLynch** [comment]
As this work is now considered abandoned, I'll close this.

Someone wanting to step up and take it on is welcome to have this re-opened and assigned to them.
