### ISSUE TITLE
Versioned docs

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/docs#259]
Hey,

currently we have many notes in the docs to show that some things are only available in specific versions. That will be more and more over time and is not good in my mind. 

We should versioning the docs so people can select their version or version-range of Bolt and get only the docs that fits for their installation. 

What do you think? I can try to edit the docs application to support versioned docs (each version has its own folder).

**Comment by GawainLynch** [comment]
Hmm… Yes… and no.  We do have a separate set for the old 1.x docs, so the base functionality is there, but could be expanded on.

Thinking out loud for a second… I personally like the way that Symfony does it, so maybe something more along those lines… Yeah, I think I like you idea.

**Comment by PhillippOhlandt** [comment]
I really like the laravel docs. http://laravel.com/docs/5.1 

They use a tagged git repo just for the markdown files. That wouldn't work here, so we can only separate them into different folders. 

Currently we have some 2.3 features in the docs what is really confusing when you overread the gray box and things don't work as described :P

**Comment by GawainLynch** [comment]
> I really like the laravel docs. http://laravel.com/docs/5.1

I double dare you to say that in IRC :laughing: 

> Currently we have some 2.3 features in the docs what is really confusing when you overread the gray box and things don't work as described :P

Yes, the a great example of a PEBCAK bug :wink: 

The thing is that 2.3 & 2.4 are going to be huge changes to internals, but 2.2 is on LTS so however it is approached needs to be obvious as the changes being implemented (2.3/2.4) are aimed at braking people out of some bad habits (that are only becoming worse due to things like the above mentioned project) and that needs to be front-and-centre **but** also not confusing to an LTS user.

**Comment by PhillippOhlandt** [comment]
So what doyou say is to do, how can I help?

**Comment by GawainLynch** [comment]
Not sure what is the best approach myself… You have drive and you're keen, so yeah I would encourage you to start *something* and get it moving, then show it off on IRC and get some feedback from the rest of the team. :+1:

**Comment by PhillippOhlandt** [comment]
thanks man :+1:

**Comment by bobdenotter** [comment]
We have this now.

**Comment by PhillippOhlandt** [comment]
W00t, pre-core-team-member issues from me :D
