### ISSUE TITLE
Install using "composer require" needs some quotes

### ISSUE THREAD

**Issue by aerth** [bolt/docs#260]
As seen on: https://docs.bolt.cm/installation-composer#adding-existing-composer-project

```php
composer require bolt/bolt ~2.2
```
needs to be:

```php
composer require 'bolt/bolt ~2.2'
```

**Comment by aerth** [comment]
Error is:

```shell
zsh: no such user or named directory: 2.2
```

**Comment by GawainLynch** [comment]
Or a colon
```php
composer require bolt/bolt:^2.2
```

**Comment by aerth** [comment]
:+1:

**Comment by johanneskonst** [comment]
Isn't it best practice to let composer figure out the current stable version?
So only `composer require bolt/bolt`

**Comment by bobdenotter** [comment]
This is fixed for v3 https://docs.bolt.cm/master/installation/composer/creating-a-new-project
