### ISSUE TITLE
Documentation in contenttypes.yml needs another url

### ISSUE THREAD

**Issue by parijke** [bolt/docs#284]
`# This file defines the contenttypes on the website. See the documentation for`
`# details: http://docs.bolt.cm/content#defining-contenttypes`

should be
`# This file defines the contenttypes on the website. See the documentation for`
`# details: https://docs.bolt.cm/contenttypes-and-records#defining-contenttypes`

**Comment by GawainLynch** [comment]
Fixed in https://github.com/bolt/bolt/commit/7d2547750ddbdc457a6b8f35674e69c113603b30
