### ISSUE TITLE
Request: add example code to /select-field-type

### ISSUE THREAD

**Issue by peterboorsma** [bolt/docs#289]
The docs give nice examplecode to show a single record using a select field (https://docs.bolt.cm/howto/select-field-type). It would be handy to add the following code to that example: fetching multiple selected records.

```
{% if record.myselectfield is not empty %}
{% set ids = record.myselectfield|join(" || ") %}
{% setcontent mycontent = 'mycontenttype' where { 'id': ids } %}
{% for mycontent in mycontenttype %}
{{ dump(mycontent) }}
{% endfor %}
{% endif %}
```

**Comment by SahAssar** [comment]
Because of #3914 you probably want to do something like this before the loop:
```
{% set mycontent = mycontent.id is defined ? [mycontent] : mycontent %}
```

**Comment by GawainLynch** [comment]
Should all be covered in https://docs.bolt.cm/fields/select now
