### ISSUE TITLE
Fix "Adding storage events" extension example

### ISSUE THREAD

**Issue by peterlcole** [bolt/docs#290]
https://docs.bolt.cm/extensions/essentials#adding-storage-events

The example

```
$app['dispatcher']->addListener(\Bolt\Events\StorageEvents::POST_SAVE, array('MyClass', 'postSaveCallback'));

function postSaveCallback(\Bolt\Events\StorageEvent $event)
{
    $id = $event->getId();
    $contentType = $event->getContentType();
    $entry = date('Y-m-d H:i:s').' '.$contentType.' with id '.$id.' has been saved'."\n";
    file_put_contents('storage.log', $entry, FILE_APPEND);
}
```

shows the class name being attached to the listener when it should be the object itself. I.e., replace 

`$app['dispatcher']->addListener(\Bolt\Events\StorageEvents::POST_SAVE, array('MyClass', 'postSaveCallback'));` 
with 
`$app['dispatcher']->addListener(\Bolt\Events\StorageEvents::POST_SAVE, array($this, 'postSaveCallback'));`

**Comment by PhillippOhlandt** [comment]
+1

**Comment by GawainLynch** [comment]
That is not always correct… I think the point the docs was trying to make is inaccurate, but you're assuming the class loader is the listener, and that is often not the case.

…as this is totally valid:
```php
$callable = [new MyClass(), 'fooBar'];
$app['dispatcher']->addListener(StorageEvents::POST_SAVE, $callable);
```

**Comment by GawainLynch** [comment]
This was completely [rewritten in v3 docs](https://docs.bolt.cm/extensions/intermediate/events) quite some time ago, so I am going to close this for now.

If you have concerns still, please feel very free to unleash a Drop Bear in my direction, or better still PR some updated text  (I suck at writing docs, I am the first to admit it :smile:)
