### ISSUE TITLE
versions.json for Algolia

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/docs#370]
Hey,

due to recent url and version changes, we should provide an up to date `versions.json` for Algolia. 

The current process when we add/remove versions or change their names in the url is that I have to mail Algolia so they update the crawler. That isn't just stressful on active development of the docs, it also leads to downtimes of the search.

My suggestion is to provide a json file at docs.bolt.cm/versions.json with the following content:

```
[
  {
    "version": "2.2",
    "url": "https://docs.bolt.cm/2.2/"
  },
  {
    "version": "3.0",
    "url": "https://docs.bolt.cm/3.0/"
  }
]
```

In the best case, this file is created dynamically.

**Comment by GawainLynch** [comment]
Hand crafted one is online now at https://docs.bolt.cm/versions.json

**Comment by PhillippOhlandt** [comment]
We don't really need this anymore because we can add new versions via a PR to their repo.
