### ISSUE TITLE
Links in the bolt cheatsheet 404 frequently

### ISSUE THREAD

**Issue by rnbwspctrm** [bolt/docs#390]
There seems to be some kind of redirect happening into nowhere. 

For example: Section 19, the setcontent tag, ends with a link to the docs- https://docs.bolt.cm/content-fetching. It redirects to https://docs.bolt.cm/2.2/content-fetching. The real docs seem to be located at https://docs.bolt.cm/2.2/templates/content-fetching.... This has happened more frequently than not. Thanks for all the hard work, overall this is a great, soon-to-be-quick alternative to symfony.

**Comment by flug** [comment]
A pull request is ready for fix broken link #408

**Comment by bobdenotter** [comment]
Fixed in #408
