### ISSUE TITLE
404 - Page not found 

### ISSUE THREAD

**Issue by nestordedios** [bolt/docs#405]
In Testing Your Extensions page there is a link which renders a 404 page not found. It´s at the Phase 1 of Testing Locally title. https://docs.bolt.cm/3.0/extensions/basics/testing#testing-locally

![captura](https://cloud.githubusercontent.com/assets/6607455/15275427/cc5704c8-1acb-11e6-9258-b990492f33a3.PNG)

**Comment by flug** [comment]
Issue is resolved with this pull request #412 @bobdenotter

**Comment by GawainLynch** [comment]
:+1:
