### ISSUE TITLE
Error on Official Bolt Website

### ISSUE THREAD

**Issue by mr-klaatu** [bolt/docs#434]
There is a bug on the official Bolt Website.

The page to submit a site at https://bolt.cm/submit-to-showcase generates the following error:

"Rendering a record Twig snippet failed: Unknown "simpleform" function."

![screen shot 2016-06-26 at 15 12 49](https://cloud.githubusercontent.com/assets/1759324/16387578/b308f198-3c95-11e6-8f88-6a213002555d.png)

**Comment by SahAssar** [comment]
I don't have access to the extensions on the site (just the content), but I thought we transitioned that to boltforms... I'll poke around.

**Comment by GawainLynch** [comment]
Should be good to go now, thank you!
