### ISSUE TITLE
Add some words about translations inclusion on extension

### ISSUE THREAD

**Issue by nbehier** [bolt/docs#493]
If I well understood, in Bolt 3.1, translations will be automatically included in extension. Could you add some word on the doc about it
https://github.com/bolt/bolt/blob/release/3.1/src/Extension/TranslationTrait.php

**Comment by GawainLynch** [comment]
@Raistlfiren I don't suppose you have some spare time to follow up with docs for that PR? If not, let us know, as @nbehier is right — it'd be good to have at least the basics — and the task should be allocated otherwise :smile:

**Comment by nbehier** [comment]
@Raistlfiren @GawainLynch @PhillippOhlandt You're awesome guys! Thanks!
