### ISSUE TITLE
User manual repository

### ISSUE THREAD

**Issue by jtraulle** [bolt/docs#52]
Hi, not really an issue here, it is just a question.

Is there a repository for user documentation that can be found at http://manual.bolt.cm

I'm French and I started the translation of the user manual.

Are there a way to give back :revolving_hearts: the translated pages to the project when done ?
I found **bolt/bolt-docs** but it is just about technical/developer documentation.

**Comment by GawainLynch** [comment]
http://manual.bolt.cm & http://docs.bolt.cm have been merged since 3.0.

Unfortunately we don't have a translation layer, nor the resource to implement it at present, so I am going to close as part of a spring clean.
