### ISSUE TITLE
Incorrect option in Image Field Docs

### ISSUE THREAD

**Issue by rossriley** [bolt/docs#528]
As seen here: https://docs.bolt.cm/3.1/fields/image

As far as I can see we have never supported `accept_file_types` as an option at the field level, this should instead be `extensions` the former is correct in the general config, but the latter at field level.

Edit: looks as though this applies to all file field docs: `file`, `filelist`, `image` and `imagelist`

**Comment by GawainLynch** [comment]
@PhillippOhlandt do you want to catch this in your current work that you're doing "today"?

**Comment by PhillippOhlandt** [comment]
Well, not templating related but I can do it.

**Comment by PhillippOhlandt** [comment]
fixed in #529 :)
