### ISSUE TITLE
Sitemap.xml. The documentation site should have it. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/docs#544]
For better indexing by the googles and such.

**Comment by CarsonF** [comment]
I didn't think sitemaps mattered that much anymore. Can't google just spider it?

Pls don't make me do xml 😢

**Comment by GawainLynch** [comment]
Yeah, I resubmitted our indexes back on the 8th of August (and again just now) but it just won't dump the old stuff and recommends the sitemap…

… and no, don't stress … I can handle it … once I've had some down time.

**Comment by bobdenotter** [comment]
I think even I could do it. :-)

**Comment by CarsonF** [comment]
Go for it, as long as it's not static :)

**Comment by GawainLynch** [comment]
What is this word "static" that you used? :wink:

**Comment by CarsonF** [comment]
Hehe I don't want to see a `sitemap.xml` file being committed 🔫

**Comment by GawainLynch** [comment]
Fixed in #545
