### ISSUE TITLE
Docs Application builds cache when debug on

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/docs#547]
I have debug set to `true` but the site still builds the cache. Is it supposed to do that?

**Comment by bobdenotter** [comment]
In my understanding, twig always uses the cache. The difference is that when `debug` is on, it _always_ parses the templates, and never uses compiled pages from cache.

**Comment by PhillippOhlandt** [comment]
Ah ok. I am not sure if I had problems. While fixing the links in the cheatsheet, I noticed that changes were not shown. But now I am not sure if I just looked at the online docs instead of my local one or if it was because of the cache :D

**Comment by CarsonF** [comment]
Yes cache is always created, for both twig and our markdown pages. Debug controls cache invalidation / freshness checks. If debug is off cache files are never validated against source files. So to see changes you need to clear cache yourself.

**Comment by PhillippOhlandt** [comment]
Ok, then I just failed at looking at the right docs earlier :D Will close this until I ~~fail again~~ experience something weird.
