### ISSUE TITLE
Code blocks in tables don't quite look consistent

### ISSUE THREAD

**Issue by GawainLynch** [bolt/docs#557]
I :heart: :heart: :heart: the new tables, and this might be an eyesight thing, but:

![image](https://cloud.githubusercontent.com/assets/1427081/19955075/11031cb8-a17e-11e6-8ec1-32d13c6c69fa.png)

The `name` doesn't look consistent with `singular_name` … font yes, but "name" looks highlighted on the white row background, while at least to me, the "singular_name" doesn't seem to be distinct in the same way. Yes, looking at 500% zoom if almost looks like it's the same, but pretty sure people don't generally surf in that mode.

I suck at UI/UX so close on me if you all disagree.

**Comment by bobdenotter** [comment]
This is because the difference between the even / odd table rows is about the same as the background color for `<code>`. I'll fix that!

**Comment by GawainLynch** [comment]
Yeah, figured that was it … but wasn't sure if it was a valid UX concern.

**Comment by bobdenotter** [comment]
UX isn't nearly as subjective as you might think. If _you_ perceive something as not clear, that means there's a UX issue. :-)

**Comment by bobdenotter** [comment]
Fixed in #559
