### ISSUE TITLE
Deploying a website from a Git installation

### ISSUE THREAD

**Issue by Cyrillius** [bolt/docs#585]
Hello!

I have installed bolt on my local machine via `git clone` and  I starded developping. Now I want to deploy my website on production web server. Do we have some tools to generate a dist folder with only required files? Or at least to have also this structure:
├── app/
├── extensions/
├── public/
├── vendor/
├── README.md
├── composer.json
└── composer.lock

I didn't find any information about this inside the documentation...

Thanks,

Cyril Praz

**Comment by GawainLynch** [comment]
Cloning the base install via git is only supported for for doing development on Bolt internals itself.

To get the structure above using a [Composer based install](https://docs.bolt.cm//installation/composer/creating-a-new-project) will set up things like that for you, you can then commit to your own site git repo and use that to deploy, or plain old `rsync` or FTP, etc.
