### ISSUE TITLE
Service Provider Registration

### ISSUE THREAD

**Issue by cdowdy** [bolt/docs#613]
According to the docs (https://docs.bolt.cm/3.2/extensions/intermediate/service-providers#creating-service-providers) to "register" a service provider you do the following:  

```php  
 public function getServiceProviders()
    {
        $parentProviders = parent::getServiceProviders();
        $localProviders = [
            new Provider\KoalaServiceProvider($this->getConfig()),
        ];

        return $parentProviders + $localProviders;
    }  
```  

In the latest stable release of Bolt 3.2.2 this will give you an exception similar too:  

```An exception has been thrown during the rendering of a template ("Identifier "your provider name here" is not defined.")``` 

According to the Extension Stencil to register a provider you do   

```php  
    public function getServiceProviders()
    {
        return [ 
            $this,
            new Proivder\KoalaServiceProvider($this-getConfig()),
        ]
    }
``` 

I used the extension stencil since others don't register any providers.  

Is this a doc's mismatch or something else?  

If it's a docs mismatch I have a pull ready to fix this

**Comment by GawainLynch** [comment]
Fixed in #613
