### ISSUE TITLE
API documentation is missing.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/docs#621]
As linked here, for example: https://docs.bolt.cm/3.2/core-development

**Comment by mborn319** [comment]
Just came across this myself and was going to create an issue.

**Comment by GawainLynch** [comment]
https://docs.bolt.cm/api

**Comment by GawainLynch** [comment]
Fixed in 02e70023f5e93fc2e2a9c8494fcaab8dc29a89f4 and deployed recent changes while I was at it.
