### ISSUE TITLE
Page update required: The Bolt JS and CSS assets

### ISSUE THREAD

**Issue by GawainLynch** [bolt/docs#666]
@see https://docs.bolt.cm/3.2/internals/javascript_css_build

**Comment by GawainLynch** [comment]
@bobdenotter assigning to you, firstly so it doesn't get lost, secondly as I have a feeling you have most/all of this already in motion or done somewhere.

**Comment by Boorj** [comment]
also this link is broken: https://github.com/bolt/docs/blame/3.0/docs/extensions/intermediate/web-assets.md#L24 . Probably because this page is unreachable : https://github.com/bolt/docs/blame/3.0/docs/howto/installing-local-extensions.md#L4

**Comment by GwendolenLynch** [comment]
Looking through my list of issues, I think I forgot to close this one a year or two ago. Feel free to reopen if you need a tacker on this one, @bobdenotter
