### ISSUE TITLE
Thumbs not generated

### ISSUE THREAD

**Issue by onerkript** [bolt/docs#706]
I'm using Bolt current version (3.2.9). When I upload images the thumbnails are neither generated or showing in the admin. My files are correctly uploaded in the /public/files folder but the /public/thumbs folder stays empty. What am I doing wrong? Thanks in advance.

**Comment by bobdenotter** [comment]
Hi, 

If you right-click one of the thumbnails, and open it in a new Tab or Window, it will most likely tell you which PHP library you are missing. Probably one of the ones listed here: https://docs.bolt.cm/3.2/getting-started/requirements

**Comment by onerkript** [comment]
Thanks for your reply. I'm getting this message:

Fatal error: Class 'finfo' not found in /var/www/litaliechezvous/pub/vendor/league/flysystem/src/Adapter/Local.php on line 307

ClassNotFoundException in Local.php line 307:
Attempted to load class "finfo" from the global namespace.
Did you forget a "use" statement?

Is it the fileinfo extension I'm missing?

**Comment by bobdenotter** [comment]
Yes. :-)

**Comment by onerkript** [comment]
Ok, thank you, will contact my host and see what he can do about this.
