### ISSUE TITLE
Where is real documentation?

### ISSUE THREAD

**Issue by Tommixoft** [bolt/docs#763]
Hi i first time using this cms looked so good until now-documentation is soooooooooooo small. and basicly on non important stuff.

Where is documentation on how to use DB class (insert, update and so on), how to get current user, current page and so on..i mean PHP related stuff. Thanks.

**Comment by SahAssar** [comment]
> documentation is soooooooooooo small

We'd like to have more docs, but there are only so many hours in the day. We very much welcome contributions though 😉 

> basicly on non important stuff

Perhaps it seems non-important to you, but for a lot of people the basics are the hardest to figure out. For more advanced stuff reading the code is probably the easiest way to learn for now.

> DB class (insert, update and so on)

We have storage docs here: https://docs.bolt.cm/3.2/extensions/storage/introduction

> how to get current user

You get it with `$app['users']->getCurrentuser()`, for stuff like this I think it's currently best to browse the code and see how it's done in our core code.

> current page and so on

For stuff like this we mainly use silex/symfony components, so for example `$app['request']` contains the request object which shows for example the url, which route was matched, which routing params were included in the url and so on. We'd prefer not to duplicate the silex/symfony docs, so for those components we defer to them. It'd be nice to have a list of links to those docs though, that is something we should work on.

**Comment by Tommixoft** [comment]
Thanks!

**Comment by SahAssar** [comment]
I'm gonna close this, if there are any specific areas that are wrong or that we need to expand please open issues for them 😄
