### ISSUE TITLE
"403 Forbidden" in docs

### ISSUE THREAD

**Issue by MauBoy** [bolt/docs#776]
Hey guys,

I've just installed bolt and read your docs. While reading I found an "403 Forbidden"-error on the page "https://docs.bolt.cm/3.2/installation/permissions". The first link with  "... Bolt File System Permissions (flat structure) ..." is affected. The current URL is "https://docs.bolt.cm/3.2/installation/permissions-flat-strucure.md". I don't know the correct URL for this link, maybe you do?

Greetings
Maurice

PS: Screenshot :)
![bolt-403](https://user-images.githubusercontent.com/28751336/28435623-0c8f96ba-6d94-11e7-8fa2-9b369df8ebf8.png)

**Comment by GawainLynch** [comment]
A sweet … Looks like I got one of the recent 301 redirects wrong. Thanks for pointing it out :+1:

**Comment by GawainLynch** [comment]
Not even, it was a derp in the actual Markdown. Fixed in ba9e95bedb5aeb3a3492e4cad48facaff76139c2 and will be deployed in about 10 minutes :+1:

**Comment by MauBoy** [comment]
Thanks for fixing it!

**Comment by GawainLynch** [comment]
Thanks for taking the time to point it out, it was quite an interesting little derp too :smile_cat:
