### ISSUE TITLE
Documentation - `server:start` should be `server:run`

### ISSUE THREAD

**Issue by edent** [bolt/docs#806]
Documentation on https://docs.bolt.cm/3.3/installation/quick-install says:

`php app/nut server:start`

But that results in this error

```
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "server:start" is not defined.                          
  Did you mean this?                                              
      server:run 
```

Running `php app/nut server:run` works

**Comment by GawainLynch** [comment]
Ooops! Thanks for pointing it out :smile:
