### ISSUE TITLE
Broken link in "Upgrading from 2.2 to 3.3 guide" - moving-22-30-basic.md

### ISSUE THREAD

**Issue by mborn319** [bolt/docs#810]
Fairly self-explanatory. From the docs page, while reading https://docs.bolt.cm/3.3/upgrading/moving-22-30-basic, I read on "Consult the documentation on [Routing](https://docs.bolt.cm/3.3/templating/templates-routes#routing) for details." Clicking "Routing" results in a 404 page.

**Comment by GawainLynch** [comment]
PR(s) incoming I'll assume :wink:

**Comment by mborn319** [comment]
@GawainLynch That's what I had planned, but I don't really understand the relative URLs in these docs and how they're built.

https://docs.bolt.cm/3.3/configuration/routing
