### ISSUE TITLE
routing.yml links to non-existent page

### ISSUE THREAD

**Issue by leggewie** [bolt/docs#834]
routing.yml links to https://docs.bolt.cm/templates/templates-routes#routing which does not exist.

**Comment by GawainLynch** [comment]
@bobdenotter could you be so kind as to confirm that link should be https://docs.bolt.cm/templating/linking-in-templates and if so I'll at least handle the Nginx 301

**Comment by bobdenotter** [comment]
@GawainLynch It should be https://docs.bolt.cm/configuration/routing 

I'll PR the fix to `routing.yml`.

Thanks for the heads-up, @leggewie

**Comment by GawainLynch** [comment]
Redirect also in place. Thanks again, @leggewie

**Comment by leggewie** [comment]
Thanks for the quick fix, guys!
