### ISSUE TITLE
Need download link to Bolt V.2 Themes

### ISSUE THREAD

**Issue by hikmatsp** [bolt/docs#937]
I've tried to search the themes for old version of Bolt CMS 2.2 via Google but none available. Some of them are redirecting to the version 3 though... If you could provide it, it would be much appreciated.

PS:
[in this official documentation](https://docs.bolt.cm/2.2/templates/templates-routes), it returns a 404 code.

**Comment by SvanteRichter** [comment]
Most of them still have a version in the marketplace for bolt 2, for example https://market.bolt.cm/view/jowy/html5up-striped has a v1 for bolt 2 and a v2 for bolt 3.
