### ISSUE TITLE
[Reminder] https://docs.bolt.cm/api/bolt/bolt/3.6/ has been moved to https://docs.bolt.cm/api/bolt/bolt/3.x/

### ISSUE THREAD

**Issue by Daryadi-S** [bolt/docs#949]
Just reminder that https://docs.bolt.cm/api/bolt/bolt/3.6/ has been moved to  https://docs.bolt.cm/api/bolt/bolt/3.x/ in https://docs.bolt.cm/3.6/core-development . Thank God Google saved my day by finding them :v

**Comment by JarJak** [comment]
Nice catch @Daryadi-S ! Unfortunately I'm not sure if those API docs are up-to-date.
