### ISSUE TITLE
[BUG] Search isn't working on bolt 4 docs

### ISSUE THREAD

**Issue by zomars** [bolt/docs#973]
Whatever you type, it doesn't bring any results:

<img width="551" alt="image" src="https://user-images.githubusercontent.com/3504472/67874588-5fee6780-faf2-11e9-92d7-4329c7142e8c.png">

**Comment by bobdenotter** [comment]
Is this on v4? If so, i'll need to add that to Algolia's config on their repo, here: https://github.com/algolia/docsearch-configs/blob/master/configs/bolt.json

**Comment by zomars** [comment]
Yes @bobdenotter it’s on v4

**Comment by zomars** [comment]
This is also happening with the new 3.7 docs

**Comment by bobdenotter** [comment]
Good catch, thanks! :-)

**Comment by bobdenotter** [comment]
@zomars It's working for 3.7 now.. When docs for 4.0 have been updated, we'll make sure those are indexed too. :-)

**Comment by zomars** [comment]
Another thing, if you're using firefox, be sure to disable Enhanced Tracking protection or the search won't work:

![image](https://user-images.githubusercontent.com/3504472/70647682-c349da00-1c06-11ea-8264-e93cc0fda5b1.png)

**Comment by bobdenotter** [comment]
Opened a PR to add v4 to search. https://github.com/algolia/docsearch-configs/pull/1610

**Comment by bobdenotter** [comment]
This is done.
