### ISSUE TITLE
The docs version select is not redirecting

### ISSUE THREAD

**Issue by zomars** [bolt/docs#976]
There's no javascript errors in the console, I think it could have to do with the DOMContentLoaded event that's is not triggering

![docs-bolt-redirect-issue](https://user-images.githubusercontent.com/3504472/70333594-03711d00-1801-11ea-802c-310adfa787a7.gif)

**Comment by bobdenotter** [comment]
This should be fixed by now, right?

**Comment by zomars** [comment]
I can confirm it's working as intended now.

**Comment by bobdenotter** [comment]
Cool, closing then
